ToDoAppLatest/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoAppLatest.Data;
using ToDoAppLatest.Models;
using ToDoAppLatest.Models.ViewModel;

namespace ToDoAppLatest.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SettingsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            SettingsVM settingsVM = LoadData();
            return View(settingsVM);
        }

        [HttpPost]
        public IActionResult Index(SettingsVM toDo)
        {
            if (toDo.ToDoType.ToDoTypeId > 0)//edit
            {
                //var res = _context.ToDoType.Where(x => x.ToDoTypeId == toDo.ToDoType.ToDoTypeId).SingleOrDefault();
                _context.ToDoType.Update(toDo.ToDoType);
                _context.SaveChanges();
            }
            else if (_context.ToDoType.Where(x => x.Name == toDo.ToDoType.Name).SingleOrDefault() == null)
            {
                _context.ToDoType.Add(toDo.ToDoType);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        private SettingsVM LoadData()
        {
            SettingsVM settingsVM = new SettingsVM();
            List<SettingObj> Settings = new List<SettingObj>();
            foreach (var obj in _context.ToDoType.ToList())
            {
                Settings.Add(new SettingObj { Id = obj.ToDoTypeId, Name = obj.Name });
            }
            settingsVM.Settings = Settings;
            settingsVM.ToDoType = new ToDoType();
            return settingsVM;
       
        }
        [HttpDelete]
        public bool DeleteToDoType(int id)
        {
            var obj = _context.ToDoType.Where(x => x.ToDoTypeId == id).SingleOrDefault();
            var res = _context.ToDoType.Remove(obj);
            _context.SaveChanges();
            return true;
        }
    }

}

ToDoAppLatest/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoAppLatest.Repository;
using ToDoAppLatest.Models.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDoAppLatest.Models;
using Microsoft.AspNetCore.Authorization;

namespace ToDoAppLatest.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        private readonly IToDoRepository _repo;
        private readonly IToDoTypeRepository _typeRepo;
       
        public ToDoController(IToDoRepository repo,IToDoTypeRepository typeRepo)
        {
            _repo = repo;
            _typeRepo = typeRepo;
            

        }
        public IActionResult Index()
        {
            var res = _repo.GetToDoList();
            List<ToDoModel> list = new List<ToDoModel>();
            foreach (var item in res)
            {
                var typeName = _typeRepo.GetTypeById(item.ToDoType).Name;
                list.Add(new ToDoModel
                {
                    Description = item.Description,
                    From = item.From,
                    FromTime = item.FromTime,
                    Id = item.Id,
                    To = item.To,
                    ToDoType = item.ToDoType,
                    ToTime = item.ToTime,
                    ToDoTypeName = typeName
                });
            }
            ToDoVM vm = new ToDoVM();
            vm.ToDoList = list;
            return View(vm);
            
        }
        public IActionResult CreateToDo()
        {
            var selectList = _typeRepo.GetAllType();
            var selectItemToDoType = new List<SelectListItem>();
            foreach (var item in selectList)
            {
                selectItemToDoType.Add(new SelectListItem { Text = item.Name, Value = item.ToDoTypeId.ToString() });
            }
            ViewBag.SelectItemToDoType = selectItemToDoType;
            ToDo obj = new ToDo();
            return View(obj);
            
        }
        public IActionResult Edit(int id)
        {
            var todoObj = _repo.GetToDoById(id);
            var selectList = _typeRepo.GetAllType();
            var selectItemToDoType = new List<SelectListItem>();
            foreach (var item in selectList)
            {
                if (todoObj.ToDoType == item.ToDoTypeId)
                {
                    selectItemToDoType.Add(new SelectListItem { Text = item.Name, Value = item.ToDoTypeId.ToString(), Selected = true });
                }
                else
                {
                    selectItemToDoType.Add(new SelectListItem { Text = item.Name, Value = item.ToDoTypeId.ToString() });
                }
            }
            ViewBag.SelectItemToDoType = selectItemToDoType;
            return View(todoObj);
        }
        [HttpPost]
        public IActionResult Index(ToDoVM vm)
        {  
            return View (vm);
        }
        [HttpPost]
            public IActionResult CreateToDo(ToDo obj)
            {
            _repo.SaveToDo(obj);
            var selectList = _typeRepo.GetAllType();
            var selectItemToDoType = new List<SelectListItem>();
            foreach (var item in selectList)
            {
                selectItemToDoType.Add(new SelectListItem { Text = item.Name, Value = item.ToDoTypeId.ToString() });
            }
            ViewBag.SelectItemToDoType = selectItemToDoType;
            return Redirect("~/ToDo/Index");
            }
        
        [HttpPost]
        public IActionResult Edit(ToDo obj)
        {
            _repo.UpdateToDo(obj);
            return RedirectToAction("Index");
        }

    }
}

ToDoAppLatest/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoAppLatest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/ToDoAppLatest.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @*  <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoAppLatest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> *@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoAppLatest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoAppLatest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoAppLatest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoAppLatest.styles.css" asp-append-version="true" />
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoAppLatest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">ToDo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                       

                       

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoAppLatest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>